### PR TITLE
Positioning - fixed overlapping nodes on `custom` config

### PR DESCRIPTION
**Pull request by shari09**
The nodes no longer overlap with one another (resolving #33).

old: 
image

new:
image

### CODE REVIEW

**Comment by shari09** [comment]
This doesn't auto-zoom + pan to the center (I manually zoomed out to take the screenshot) but @kc-leung is figuring out a similar functionality to fix the builder/requestDetails's `Flow` not centering so I'll leave that :))

**Review by kc-leung — COMMENTED** [review]
- new react-flow version has a different data structure for source & target
- new version is needed for positioning & auto centre fitView

**Comment by kc-leung** [comment]
- Added lastest version of react-flow-renderer
- Now requieres target/source nodes <Handle> in order to create a connection whereas before it wasn't necessary as long as the link is created
- Added hook to autofit center view on render

To Do:

- Refactor is needed to use some of the added lastest feature 
- <Handle> component in dagNode should be render based on existing target/source instead of level

**Comment by woozyking** [comment]
@kc-leung can you test this in snoke with https://classic.yarnpkg.com/en/docs/cli/link/ and see if the new flow library version doesn't cause breaking issues on snoke?

**Review by kc-leung — APPROVED** [review]

**Review by woozyking — CHANGES_REQUESTED** [review]
@kc-leung can we remove the `.DS_Store` file (and add an entry in `.gitignore` to ignore future occurrence)

also before merging maybe we can change version to `0.6.3`. also for future reference the alpha this time should have been `0.6.3-alpha` to denote that it's a future version beyond the existing 0.6.2

**Review by woozyking — APPROVED** [review]

**Pull request merged**
